### ISSUE TITLE
Trimmed text

### ISSUE THREAD

**Issue by aldrinlsc** [uouapps/medico#12]
![trimmed-text](https://cloud.githubusercontent.com/assets/972309/12550388/5d403110-c39e-11e5-9d05-81f81bb7cf92.jpg)

Please add a 25px padding for the left and right side of the box. Also the text should not be trimmed like the one in the first box.

**Comment by rashedInt32** [comment]
@aldrinlsc  if we remove text trimmed then it would be mess with grid layout. Pleae reconsider the trimmed one i added the padding both side. Thanks
