### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by aktar56** [uouapps/medico#19]
http://prntscr.com/9w03cy

**Comment by aktar56** [comment]
![mGflPOV.png](https://files.zenhub.io/56af02b1a7478d240dd89f1e)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by aktar56** [comment]
![mgflpov](https://cloud.githubusercontent.com/assets/13032894/12710761/f4ee79e6-c8e3-11e5-9dd4-b607a2e51d49.png)

**Comment by rashedInt32** [comment]
done
