### ISSUE TITLE
Footer layout

### ISSUE THREAD

**Issue by aldrinlsc** [uouapps/medico#7]
![footer](https://cloud.githubusercontent.com/assets/972309/12485908/4eff5c3a-c09b-11e5-9b83-264c067dbac0.jpg)

Follow the footer layout based on attached image. The current footer on the demo
looked different: http://medical.uouapps.com/

**Comment by aktar56** [comment]
Twitter & Photostream are not relevant of Medical Directory. 
We have created two Widget for the footer instate of Twitter & Photostream.
1. Latest Hospital Widget
2. Latest Doctor Widget

**Comment by aldrinlsc** [comment]
Ok but can we atleast make the logo in the footer smaller? right now it's too big and it's bigger than the logo in header. 

2nd) The font style of address needs to be the same as the font style from newsletter. 

3rd) Kindly add more tags in the tag section so the overall footer layout looked more balance.

4th) The icons in the address needs to be #333333. Same thing with the headings in the footer. Please refer to the attached file

**Comment by rashedInt32** [comment]
done , tag will be add by Aktar
